DdJob.Web/Models/Layout/HeaderViewModel.cs
namespace DdJob.Web.Models.Layout
{
    public class HeaderViewModel
    {
        public string Name { get; set; }
        public string UserName { get; set; }
        public string UserType{ get; set; }
        public string DisplayInfo{ get; set; }
        public string CreationTime { get; set; }
        public int MessageCount { get; set; }
    }
}

DdJob.Web/Models/Layout/LeftSideViewModel.cs
using System.Collections.Generic;
using DdJob.Application.Roles.Dto;

namespace DdJob.Web.Models.Layout
{
    public class LeftSideViewModel
    {
        public string UserName { get; set; }
        public string Name { get; set; }        
        public List<PermissionDto> GrantedPermissions { get; set; }
    }
}

DdJob.Web/Models/Layout/TopMenuViewModel.cs
using Abp.Application.Navigation;

namespace DdJob.Web.Models.Layout
{
    public class TopMenuViewModel
    {
        public UserMenu MainMenu { get; set; }

        public string ActiveMenuItemName { get; set; }
    }
}

DdJob.Web/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Configuration.Startup;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using DdJob.Application.Sessions;
using DdJob.Application.Users;
using DdJob.Web.Models.Layout;

namespace DdJob.Web.Controllers
{
    public class LayoutController : ControllerBase
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly ISessionAppService _sessionAppService;
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly ILanguageManager _languageManager;
        private readonly IUserService _userService;

        public LayoutController(
            IUserNavigationManager userNavigationManager,
            ISessionAppService sessionAppService,
            IMultiTenancyConfig multiTenancyConfig,
            ILanguageManager languageManager,
            IUserService userService)
        {
            _userNavigationManager = userNavigationManager;
            _sessionAppService = sessionAppService;
            _multiTenancyConfig = multiTenancyConfig;
            _languageManager = languageManager;
            _userService = userService;
        }

        [ChildActionOnly]
        public PartialViewResult TopMenu(string activeMenu = "")
        {
            var test = _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.ToUserIdentifier());
            var model = new TopMenuViewModel
            {
                MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.ToUserIdentifier())),
                ActiveMenuItemName = activeMenu
            };

            return PartialView("_TopMenu", model);
        }
        //[ChildActionOnly]
        //public PartialViewResult UserMenuOrLoginLink()
        //{
        //    UserMenuOrLoginLinkViewModel model;

        //    if (AbpSession.UserId.HasValue)
        //    {
        //        model = new UserMenuOrLoginLinkViewModel
        //        {
        //            LoginInformations = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations()),
        //            IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
        //        };
        //    }
        //    else
        //    {
        //        model = new UserMenuOrLoginLinkViewModel
        //        {
        //            IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled
        //        };
        //    }

        //    return PartialView("_UserMenuOrLoginLink", model);
        //}


        [ChildActionOnly]
        public PartialViewResult AdminLteLeftSideBar()
        {
            var current = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations());

            var model = new LeftSideViewModel()
            {
                UserName = current != null ? current.User.UserName : "",
                Name = current != null ? current.User.Name : "",
                GrantedPermissions = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentAllGrantedPermissions())
            };

            return PartialView("_AdminLteLeftSideBar", model);
        }

        [ChildActionOnly]
        public PartialViewResult AdminLteHeader()
        {
            var model = new HeaderViewModel();
            var user = _userService.GetEntityDtoById(AbpSession.GetUserId());
            if (user != null)
            {
                model.Name = user.Name;
                model.UserName = user.UserName;
                model.UserType = user.UserTypeText;
                model.CreationTime = user.CreationTime.ToString(DefaultString.DefaultShortDate);
            }

            return PartialView("_AdminLteHeader", model);
        }

        [ChildActionOnly]
        public PartialViewResult WinxinLeftSideBar()
        {
            var current = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations());

            var model = new LeftSideViewModel()
            {
                UserName = current != null ? current.User.UserName : "",
                Name = current != null ? current.User.Name : "",
                GrantedPermissions = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentAllGrantedPermissions())
            };

            return PartialView("_WinxinLeftSideBar", model);
        }
        [ChildActionOnly]
        public PartialViewResult WinxinHeader()
        {
            var model = new HeaderViewModel();
            var user = _userService.GetEntityDtoById(AbpSession.GetUserId());
            if (user != null)
            {
                model.UserName = user.UserName;
                model.UserType = user.UserTypeText;
                model.CreationTime = user.CreationTime.ToString(DefaultString.DefaultShortDate);
            }

            return PartialView("_WeixinHeader", model);
        }
    }
}

DdJob.Web/Views/Shared/_AdminLTELayout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>@ViewBag.Title</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport" />
    <link rel="stylesheet" href="~/css/bootstrap/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/ionicons.min.css" />
    <link rel="stylesheet" href="~/js/plugins/jvectormap/jquery-jvectormap-1.2.2.css" />
    <link rel="stylesheet" href="~/js/plugins/datatables/dataTables.bootstrap.css">
    <link rel="stylesheet" href="~/css/AdminLTE/AdminLTE.min.css" />
    <link rel="stylesheet" href="~/css/kendo/kendo.bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/kendo/kendo.common-bootstrap.core.min.css" />
    <link rel="stylesheet" href="~/css/kendo/kendo.common-bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/main.css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/css/AdminLTE/skins/_all-skins.min.css" />

    @Styles.Render("~/Bundles/vendor/css")
    @Styles.Render("~/Bundles/css")
    <link rel="icon" href="~/favicon.ico" />

    @Scripts.Render("~/Bundles/vendor/js/top")
</head>
<body class="hold-transition skin-blue sidebar-mini DdJob">
    <div class="wrapper">
        @Html.Action("AdminLteHeader", "Layout")
        @Html.Action("AdminLteLeftSideBar", "Layout")
        @RenderBody()
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>版本</b> 1.0.0
            </div>
            <strong>版权 &copy; 2017 <a href="/home">中国光大银行重庆分公司</a>.</strong> 保留所有权利.
        </footer>
        <div class="control-sidebar-bg"></div>
    </div>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/js/plugins/fastclick/fastclick.js"></script>
    <script src="~/js/AdminLTE/app.min.js"></script>
    <script src="~/js/client/base.js"></script>
    <script src="~/js/plugins/sparkline/jquery.sparkline.min.js"></script>
    <script src="~/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <script src="~/js/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <script src="~/js/plugins/chartjs/Chart.min.js"></script>
    <script src="~/js/kendo/kendo.ui.core.min.js"></script>
    <script src="~/js/kendo/kend.all.js"></script>
    @*<script src="~/js/kendo/kendo.culture.zh-CN.min.js"></script>*@
    <script src="~/js/kendo/kendo.messages.zh-CN.js"></script>
    <script src="~/js/plugins/laydate/laydate.dev.js"></script>
    <script src="~/js/plugins/fileupload/jquery.ui.widget.js"></script>
    <script src="~/js/plugins/fileupload/jquery.fileupload.js"></script>
    <script src="~/js/plugins/fileupload/jquery.iframe-transport.js"></script>
    @Scripts.Render("~/Bundles/vendor/js/bottom")
    <script src="~/js/custom.js"></script>
    <script src="~/js/DdJob.js"></script>
    <script src="~/js/bootstrap3-typeahead.js"></script>
    @Scripts.Render("~/Bundles/js")
    @RenderSection("scripts", required: false)
</body>
</html>

DdJob.Web/Views/Shared/_ClientLayout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" />
    <link href="~/JSTemplates/dist/css/client.css" rel="stylesheet" />
    <link rel="icon" href="~/favicon.ico" />

    <title>@ViewBag.Title</title>

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/vendor/js/top")

</head>
<body class="hold-transition login-page">
    @RenderBody()

    <script src="~/js/DdJob.js"></script>
    <script src="~/JSTemplates/dist/js/vendor.js"></script>
    <script src="~/JSTemplates/dist/js/client.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

DdJob.Web/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@*@using Abp.Web.Mvc.Extensions
@{
    SetAntiForgeryCookie();
}*@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="~/css/bootstrap/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css" />
    <link rel="stylesheet" href="~/js/plugins/jvectormap/jquery-jvectormap-1.2.2.css" />
    <link rel="stylesheet" href="~/css/AdminLTE/AdminLTE.min.css" />
    <link href="~/JSTemplates/dist/css/client.css" rel="stylesheet" />
    <link rel="icon" href="~/favicon.ico" />

    <title>@ViewBag.Title</title>

    @Styles.Render("~/Bundles/vendor/css")
    @Styles.Render("~/Bundles/css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/vendor/js/top")

</head>
<body class="hold-transition login-page">
    @Html.Partial("_TopBar")

    @RenderBody()

    @Scripts.Render("~/Bundles/vendor/js/bottom")
    @Scripts.Render("~/Bundles/js")

    <script>
        //Localizing momentjs
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name');
    </script>
    <script src="~/js/DdJob.js"></script>
    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
<script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>
    <script src="~/JSTemplates/dist/js/vendor.js"></script>
    <script src="~/JSTemplates/dist/js/client.js"></script>

    <!-- SignalR scripts -->
    <script src="~/signalr/hubs"></script>
    @Html.IncludeScript("~/Abp/Framework/scripts/libs/abp.signalr.js")

<!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

DdJob.Web/Views/Shared/_TopBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="~/"><i class="fa fa-cubes"></i> @L("DdJob")</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                @*@Html.Action("TopMenu", "Layout", new { activeMenu = ViewBag.ActiveMenu })*@
            </ul>
        </div>
    </div>
</div>